<meta charset="utf-8">
    <link href="css/style.css" rel="stylesheet" type="text/css" />
    <link href="css/layout.css" rel="stylesheet" type="text/css" />
<?php
class teste {
    public function form(){
        echo "<div class='sinistro'>";
        echo "<table>
        <tr><td>SINISTRO: </td><td><input type='text' name='sinistro' /></td>
        <td>APÓLICE: </td><td><input type='text' name='apolice' /></td>
        <td>CERTIFICADO: </td><td><input type='text' name='certificado' /></td>
        <td>No. RAMO: </td><td><input type='text' name='ramo' /></td>
        <td>COBERTURA: </td><td><input type='text' name='cobertura' /></td></tr>
        <tr><td>DT SINISTRO: </td><td><input type='text' name='sinistro_data' /></td>
        <td>DT AVISO: </td><td><input type='text' name='aviso_data' /></td>
        <td>DT VIGENCIA INICIAL: </td><td><input type='text' name='vigencia_data' /></td>
        <td>DT DOC OK: </td><td><input type='text' name='doc_ok' /></td></tr>
        <tr><td>TITULAR: </td><td><input type='text' name='titular' /></td>
        <td>CPF: </td><td><input type='text' name='cpf' /></td>
        <td>AV/RUA/TRAV/PÇA/ALAM: </td><td><input type='text' name='rua' /></td></tr>
        <tr><td>ENDEREÇO: </td><td><input type='text' name='endereco' /></td>
        <td>NUMERO: </td><td><input type='text' name='numero' /></td>
        <td>COMPLEMENTO: </td><td><input type='text' name='complemento' /></td></tr>
        <tr><td>BAIRRO: </td><td><input type='text' name='bairro' /></td>
        <td>CIDADE: </td><td><input type='text' name='cidade' /></td>
        <td>ESTADO: </td><td><input type='text' name='estado' /></td></tr>
        <tr><td>CEP: </td><td><input type='text' name='cep' /></td>
        <td>TEL: </td><td><input type='tel' name='tel' /></td>
        <td>EMAIL: </td><td><input type='email' name='email' /></td>
        <td>TIPO SEGURO: </td><td><input type='text' name='tipo_seguro' /></td>
        <td>IMPORTÂNCIA SEGURADA: </td><td><input type='text' name='imp_segurada' /></td></tr>";
        echo "</table>";
        echo "</div>";
    }
}

$teste = new teste();
print_r($teste -> form());

